### ISSUE TITLE
Claims that allowing requests to http://127.0.0.1 is a risk

### ISSUE THREAD

**Issue by BenjaminEHowe** [google/csp-evaluator#5] opened 2018-04-17 21:38 UTC
I don't think I need HTTPS when requests will stay within my computer. [w3c agrees](https://w3c.github.io/webappsec-secure-contexts/#is-origin-trustworthy), considering http://127.0.0.1 "potentially trustworthy", and therefore most modern browsers wouldn't warn of mixed content. Please could this tool be tweaked?

**Comment by lweichselbaum** [comment] 2020-01-30 00:15
I'm closing this as working as intended. 
Loopback addresses shouldn't be used in an production environment.

**Closed by lweichselbaum** 2020-01-30 00:15 UTC
